name: Sync luci-app-openclash and luci-app-passwall

on:
  schedule:
    - cron: "0 16 * * *"   # 北京时间 0 点
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "hatbhtbh"
          git config --global user.email "hatbhtbh@gmail.com"

      - name: Checkout OpenClash upstream
        uses: actions/checkout@v4
        with:
          repository: vernesong/OpenClash
          ref: master
          path: upstream-openclash
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Passwall upstream
        uses: actions/checkout@v4
        with:
          repository: xiaorouji/openwrt-passwall
          # 不写 ref，让它用默认分支
          path: upstream-passwall
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy target directories
        run: |
          rm -rf luci-app-openclash luci-app-passwall
          cp -r upstream-openclash/luci-app-openclash ./luci-app-openclash
          cp -r upstream-passwall/luci-app-passwall ./luci-app-passwall

      - name: Commit and Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add luci-app-openclash luci-app-passwall

          if git diff --cached --quiet; then
            echo "No changes detected, skip commit"
            exit 0
          fi

          git commit -m "Sync luci-app-openclash and luci-app-passwall from upstream"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
